# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-13 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
